ConvertFrom-StringData @'
    GetVMNetAdapter=Getting VM Network Adapter information.
    GetVMNetAdapterVlan=Getting VM Network Adapter VLAN information.
    VlanShouldntBeTagged=VM Network Adapter should not have a Vlan tag.
    VlanNotUntagged=Vlan is tagged. It will be removed.
    VlanDoesNotMatch=VlanId does not match.
    RemovingVlanTag=Removing Vlan tagging on Network Adapter.
    SettingVlan=Setting VlanId on network adapter.
    NotDhcp=Ethernet Adapter is not configured for Dhcp.
    Dhcp=Ethernet Adapter is configured for Dhcp.
    EnableDhcp=Enabling DHCP.
    IPAddressNotConfigured=IPAddress is not configured.
    GatewayNotConfigured=Gateway is not configured.
    DNSServerNotConfigured=DNS Server not configured.
    MissingIPAndSubnet=Missing IPAddress or Subnet.
    FoundVMNetAdapter=Found VM Network Adapter.
    NoVMNetAdapterFound=No VM Network Adapter found.
    StaticAddressDoesNotMatch=Staic MAC address on the VM Network Adapter does not match.
    EnableDynamicMacAddress=VM Network Adapter exists but without Dynamic MAC address setting.
    EnableStaticMacAddress=VM Network Adapter exists but without static MAC address setting.
    PerformVMNetModify=Performing VM Network Adapter configuration changes.
    AddVMNetAdapter=Adding VM Network Adapter.
    RemoveVMNetAdapter=Removing VM Network Adapter.
    VMNetAdapterExistsNoActionNeeded=VM Network Adapter exists with requested configuration. No action needed.
    VMNetAdapterDoesNotExistShouldAdd=VM Network Adapter does not exist. It will be added.
    VMNetAdapterExistsShouldRemove=VM Network Adapter Exists. It will be removed.
    VMNetAdapterDoesNotExistNoActionNeeded=VM Network adapter does not exist. No action needed.
    SwitchIsDifferent=Net Adapter is not connected to the requested switch.
    PerformSwitchConnect=Connecting VM Net adapter to the right switch.
'@
